#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="/etc/sing-box"
INSTALL_DIR="/opt/singbox-rule-ui"
MANAGER_DIR="$CONFIG_DIR/manager"
INSTALL_STATE_FILE="$MANAGER_DIR/install-state"
RADVD_STATE_FILE="$MANAGER_DIR/radvd-state.before-sing-box"
RESOLVED_STATE_FILE="$MANAGER_DIR/resolved-state.before-sing-box"
LOG_DIR="/var/log/sing-box-gateway"
LOGROTATE_CONFIG="/etc/logrotate.d/sing-box-gateway"
SYSTEMD_DIR="/etc/systemd/system"
CRON_FILE="/etc/cron.d/sing-box-gateway"
RESOLVED_DROPIN="/etc/systemd/resolved.conf.d/00-sing-box-gateway.conf"
DEB_PACKAGES=(curl ca-certificates tar gzip python3 nftables iproute2 rsync util-linux coreutils cron logrotate iputils-ping)
PURGE=0
ASSUME_YES=0

usage() {
  cat <<'EOF'
Usage:
  sudo bash scripts/uninstall.sh [--purge] [--yes]

Default uninstall removes sing-box-gateway-ui systemd services, helper scripts,
cron jobs, runtime config, generated rules, UI files, and the bundled sing-box
binary when this installer added it. apt packages that existed before
installation are kept. systemd-resolved / radvd states are restored from the
recorded pre-install snapshot.

Use --purge to also remove /usr/local/bin/sing-box when ownership cannot be
proven from the install state.
EOF
}

need_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root." >&2
    exit 1
  fi
}

ask_confirm() {
  if [ "$ASSUME_YES" = "1" ]; then
    return 0
  fi
  if [ ! -r /dev/tty ]; then
    echo "No interactive terminal. Re-run with --yes to confirm." >&2
    exit 1
  fi
  prompt="Uninstall sing-box-gateway-ui and remove all files installed by it?"
  if [ "$PURGE" = "1" ]; then
    prompt="PURGE all sing-box-gateway-ui files, configs, and /usr/local/bin/sing-box?"
  fi
  printf "%s [y/N]: " "$prompt" > /dev/tty
  read -r answer < /dev/tty
  case "$answer" in
    y|Y|yes|YES) ;;
    *) echo "Cancelled."; exit 0 ;;
  esac
}

stop_and_disable() {
  local unit="$1"
  if systemctl list-unit-files "$unit.service" >/dev/null 2>&1; then
    systemctl stop "$unit" >/dev/null 2>&1 || true
    systemctl disable "$unit" >/dev/null 2>&1 || true
    systemctl reset-failed "$unit" >/dev/null 2>&1 || true
  fi
}

cleanup_tproxy_runtime() {
  if command -v nft >/dev/null 2>&1; then
    nft delete table inet singbox_tproxy >/dev/null 2>&1 || true
    nft delete table inet singbox >/dev/null 2>&1 || true
  fi
  ip rule del fwmark 1 table 100 >/dev/null 2>&1 || true
  ip -6 rule del fwmark 1 table 100 >/dev/null 2>&1 || true
  ip route flush table 100 >/dev/null 2>&1 || true
  ip -6 route flush table 100 >/dev/null 2>&1 || true
}

state_value() {
  local key="$1" file="$2"
  [ -r "$file" ] || return 0
  awk -F= -v key="$key" '$1 == key { print substr($0, length(key) + 2); exit }' "$file"
}

restore_radvd_state() {
  if ! systemctl list-unit-files radvd.service >/dev/null 2>&1 || [ ! -r "$RADVD_STATE_FILE" ]; then
    return
  fi
  before_enabled="$(state_value enabled "$RADVD_STATE_FILE")"
  before_active="$(state_value active "$RADVD_STATE_FILE")"

  # 只按安装前记录恢复 radvd；没有记录时绝不主动广播 IPv6 默认网关。
  if [ "$before_enabled" = "enabled" ]; then
    systemctl enable radvd >/dev/null 2>&1 || true
  else
    systemctl disable radvd >/dev/null 2>&1 || true
  fi

  if [ "$before_active" = "active" ]; then
    systemctl start radvd >/dev/null 2>&1 || true
  else
    systemctl stop radvd >/dev/null 2>&1 || true
  fi
}

restore_resolved_state() {
  # 安装时若关闭了 systemd-resolved 的 stub listener，卸载按记录恢复：删掉 drop-in、精确还原 resolv.conf、重启 resolved。
  [ -e "$RESOLVED_DROPIN" ] || [ -r "$RESOLVED_STATE_FILE" ] || return 0
  rm -f "$RESOLVED_DROPIN"
  if [ -r "$RESOLVED_STATE_FILE" ]; then
    resolv_type="$(state_value resolv_conf_type "$RESOLVED_STATE_FILE")"
    resolv_target="$(state_value resolv_conf_target "$RESOLVED_STATE_FILE")"
    resolv_repointed="$(state_value resolv_repointed "$RESOLVED_STATE_FILE")"
    # 只有安装时确实动过 resolv.conf 才还原，避免覆盖用户卸载前的新配置。
    if [ "$resolv_repointed" = "1" ]; then
      if [ "$resolv_type" = "symlink" ] && [ -n "$resolv_target" ]; then
        ln -sf "$resolv_target" /etc/resolv.conf
      elif [ "$resolv_type" = "file" ] && [ -r "$MANAGER_DIR/resolv.conf.before-sing-box" ]; then
        # 普通文件（PVE/云镜像）从整份备份原样还原。
        rm -f /etc/resolv.conf
        cp -a "$MANAGER_DIR/resolv.conf.before-sing-box" /etc/resolv.conf
      fi
    fi
  fi
  if systemctl list-unit-files systemd-resolved.service >/dev/null 2>&1; then
    systemctl restart systemd-resolved >/dev/null 2>&1 || true
  fi
  echo "systemd-resolved stub listener state restored."
}

remove_generated_radvd_files() {
  for path in /etc/radvd.conf /etc/radvd.conf.bak.* /etc/radvd.conf.bak-restore-rdnss-*; do
    [ -e "$path" ] || continue
    if head -n 1 "$path" 2>/dev/null | grep -q "Generated by Sing-box UI"; then
      rm -f "$path"
    fi
  done
}

remove_sing_box_binary_if_owned() {
  owner="$(state_value sing_box_binary "$INSTALL_STATE_FILE")"
  if [ "$owner" = "installed" ] || { [ "$owner" = "" ] && [ "$PURGE" = "1" ]; }; then
    rm -f /usr/local/bin/sing-box
  fi
}

remove_installed_packages_if_owned() {
  if ! command -v apt-get >/dev/null 2>&1; then
    return
  fi
  case "${SING_BOX_GATEWAY_REMOVE_DEPS:-0}" in
    1|true|TRUE|yes|YES|on|ON) ;;
    *)
      echo "Keeping apt packages. Set SING_BOX_GATEWAY_REMOVE_DEPS=1 to remove installer-added dependencies."
      return
      ;;
  esac
  packages_to_remove=()
  for package in "${DEB_PACKAGES[@]}"; do
    if [ "$(state_value "pkg_${package}" "$INSTALL_STATE_FILE")" = "absent" ]; then
      packages_to_remove+=("$package")
    fi
  done
  if [ "${#packages_to_remove[@]}" -eq 0 ]; then
    return
  fi
  # 只卸载安装前不存在、由本安装器引入的依赖，避免误删系统基础组件。
  DEBIAN_FRONTEND=noninteractive apt-get purge -y "${packages_to_remove[@]}" || true
  DEBIAN_FRONTEND=noninteractive apt-get autoremove -y || true
}

parse_args() {
  for arg in "$@"; do
    case "$arg" in
      --purge) PURGE=1 ;;
      -y|--yes) ASSUME_YES=1 ;;
      -h|--help) usage; exit 0 ;;
      *) echo "Unknown option: $arg" >&2; usage >&2; exit 1 ;;
    esac
  done
}

main() {
  parse_args "$@"
  need_root
  ask_confirm

  echo "Stopping systemd services..."
  for service in singbox-rule-ui sing-box sing-box-tproxy singbox-mtu; do
    stop_and_disable "$service"
  done

  cleanup_tproxy_runtime
  restore_radvd_state
  restore_resolved_state

  echo "Removing cron jobs, service files, and helper scripts..."
  rm -f "$CRON_FILE"
  systemctl reload-or-restart cron >/dev/null 2>&1 || true
  rm -f \
    "$SYSTEMD_DIR/sing-box.service" \
    "$SYSTEMD_DIR/sing-box-tproxy.service" \
    "$SYSTEMD_DIR/singbox-rule-ui.service" \
    "$SYSTEMD_DIR/singbox-mtu.service" \
    "$SYSTEMD_DIR/singbox-qdisc.service" \
    /usr/local/sbin/sing-box-tproxy-setup \
    /usr/local/sbin/refresh-sing-box-runtime-config \
    /usr/local/sbin/monitor-sing-box-runtime \
    /usr/local/sbin/refresh-sing-box-tproxy-setup \
    /usr/local/sbin/update-sing-box-rules-jsdelivr \
    /usr/local/bin/sing-box-gateway-info \
    /usr/local/bin/sing-box-gateway-uninstall \
    "$LOGROTATE_CONFIG" \
    /etc/sysctl.d/99-sing-box-tproxy.conf
  # 兼容早期可能残留的 OpenRC init 脚本。
  rm -f /etc/init.d/sing-box /etc/init.d/sing-box-tproxy /etc/init.d/singbox-rule-ui
  systemctl daemon-reload >/dev/null 2>&1 || true

  remove_generated_radvd_files
  rm -rf "$INSTALL_DIR" "$LOG_DIR"
  remove_sing_box_binary_if_owned
  remove_installed_packages_if_owned
  rm -rf "$CONFIG_DIR"

  echo "Uninstalled."
}

main "$@"
